### ISSUE TITLE
out has no attribute 'data'

### ISSUE THREAD

**Issue by kalpa61** [ECNU-Cross-Innovation-Lab/GSMC#1]
hi, I'm sorry to bother you. An error occurred when I was running the code, and the data attribute was displayed as out, so I did not change the code. May I ask how to fix this error.
> Epoch [1/40], Loss: 1.9660654390851657
> Traceback (most recent call last):
>   File "GSMC.py", line 273, in <module>
>     _, predicted = torch.max(out.data, 1)
> AttributeError: 'tuple' object has no attribute 'data'

**Comment by hueujjsjiiik** [comment]
Hi,I have changed the code.

**Comment by kalpa61** [comment]
OK，Thanks
