### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by kalpa61** [ECNU-Cross-Innovation-Lab/GSMC#2]
Hello, I'm sorry to bother you again. I would like to ask about the number of rounds of training for this mv_epoch_17.pt weight, and is it only trained using RAF-DB data set? In addition, where can I get the paper?

**Comment by hueujjsjiiik** [comment]
The weight is the model pretrained on ms_celeb_1m. And the paper is accepted but not published.I will try to publish the arXiv version.

**Comment by kalpa61** [comment]
ok，thank you！
